In [1]:
# Importing Packages
import pandas as pd

In [4]:
# List of years
years_int=list(range(2001,2023))

# Convert the years into strings
years=[]
for i in years_int:
    years.append(str(i))

In [8]:
main_df=pd.DataFrame()

In [10]:
for year in years:
    df1=pd.read_csv('Database/main%s_df.csv'%year)
    main_df=pd.concat([main_df,df1])

In [12]:
main_df = main_df.iloc[: , 1:]

In [15]:
main_df_names=main_df['Name']

In [17]:
main_df=main_df.iloc[: , 1:]

In [19]:
main_df=main_df.astype(float)

In [21]:
main_df['Name']=main_df_names

In [27]:
main_df=main_df.fillna(0)

In [28]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1157 entries, 0 to 51
Data columns (total 37 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Scoring Average (Actual)                1157 non-null   float64
 1   Stroke Differential Field Average       1157 non-null   float64
 2   Par 3 Birdie or Better Leaders          1157 non-null   float64
 3   Par 4 Birdie or Better Leaders          1157 non-null   float64
 4   Par 5 Birdie or Better Leaders          1157 non-null   float64
 5   Par Breakers                            1157 non-null   float64
 6   Birdie Average                          1157 non-null   float64
 7   Bounce Back                             1157 non-null   float64
 8   Birdie to Bogey Ratio                   1157 non-null   float64
 9   Birdie or Better Percentage             1157 non-null   float64
 10  Bogey Avoidance                         1157 non-null   float64
 11  Reverse Bounce Back                     1157 non-null   float64
 12  Bogey Average                           1157 non-null   float64
 13  Driving Distance                        1157 non-null   float64
 14  Driving Accuracy Percentage             1157 non-null   float64
 15  Good Drive Percentage                   1157 non-null   float64
 16  Total Driving                           1157 non-null   float64
 17  Ball Striking                           1157 non-null   float64
 18  Greens in Regulation Percentage         1157 non-null   float64
 19  GIR Percentage from Fairway             1157 non-null   float64
 20  GIR Percentage from Other than Fairway  1157 non-null   float64
 21  Scrambling                              1157 non-null   float64
 22  One-Putt Percentage                     1157 non-null   float64
 23  1-Putts per Round                       1157 non-null   float64
 24  3-Putt Avoidance                        1157 non-null   float64
 25  3-Putts per Round                       1157 non-null   float64
 26  3+ Putts per Round                      1157 non-null   float64
 27  Putts Per Round                         1157 non-null   float64
 28  2-Putts per Round                       1157 non-null   float64
 29  Putting Average                         1157 non-null   float64
 30  Overall Putting Average                 1157 non-null   float64
 31  Birdie or Better Conversion Percentage  1157 non-null   float64
 32  Par 3 Performance                       1157 non-null   float64
 33  Par 4 Performance                       1157 non-null   float64
 34  Par 5 Performance                       1157 non-null   float64
 35  Year                                    1157 non-null   float64
 36  Name                                    1157 non-null   object
dtypes: float64(36), object(1)
memory usage: 343.5+ KB

In [29]:
main_df_columns = main_df.columns.tolist()

In [35]:
main_df_columns = ['Name','Year','Scoring Average (Actual)','Stroke Differential Field Average','Par 3 Birdie or Better Leaders','Par 4 Birdie or Better Leaders','Par 5 Birdie or Better Leaders','Par 3 Performance','Par 4 Performance','Par 5 Performance','Par Breakers','Birdie Average','Bounce Back','Birdie to Bogey Ratio','Birdie or Better Percentage','Bogey Avoidance','Reverse Bounce Back','Bogey Average','Driving Distance','Driving Accuracy Percentage','Good Drive Percentage','Total Driving','Ball Striking','Greens in Regulation Percentage','GIR Percentage from Fairway','GIR Percentage from Other than Fairway','Scrambling','One-Putt Percentage','1-Putts per Round','3-Putt Avoidance','3-Putts per Round','3+ Putts per Round','Putts Per Round','2-Putts per Round','Putting Average','Overall Putting Average','Birdie or Better Conversion Percentage']

In [36]:
main_df=main_df[main_df_columns]

In [38]:
main_df.to_csv('csv/main_allyears_df.csv')

In [39]:
main_df.describe()

,Year,Scoring Average (Actual),Stroke Differential Field Average,Par 3 Birdie or Better Leaders,Par 4 Birdie or Better Leaders,Par 5 Birdie or Better Leaders,Par 3 Performance,Par 4 Performance,Par 5 Performance,Par Breakers,...,One-Putt Percentage,1-Putts per Round,3-Putt Avoidance,3-Putts per Round,3+ Putts per Round,Putts Per Round,2-Putts per Round,Putting Average,Overall Putting Average,Birdie or Better Conversion Percentage
count,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,...,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000,1157.000000
mean,2011.924806,72.372515,0.891029,13.348099,12.512965,42.491357,3.341167,4.133189,4.657882,19.360424,...,38.353457,6.903630,4.469265,0.786949,0.017286,29.437338,10.051210,1.813905,1.635408,28.060242
std,6.275292,1.653237,1.358776,8.518978,5.300226,13.428026,7.818625,0.114027,0.195719,4.768945,...,5.649134,1.016837,2.496429,0.442872,0.064299,1.243524,1.037272,0.080176,0.069075,8.301825
min,2001.000000,67.000000,-3.480000,0.000000,0.000000,0.000000,2.690000,3.750000,4.060000,4.170000,...,22.220000,4.000000,0.000000,0.000000,0.000000,25.250000,6.500000,1.561000,1.403000,1.960000
25%,2007.000000,71.500000,0.040000,6.250000,7.500000,31.250000,3.000000,4.050000,4.560000,16.670000,...,34.720000,6.250000,2.780000,0.500000,0.000000,28.500000,9.500000,1.762000,1.583000,24.140000
50%,2012.000000,72.250000,0.860000,12.500000,12.500000,43.750000,3.130000,4.130000,4.690000,19.440000,...,38.890000,7.000000,4.170000,0.750000,0.000000,29.500000,10.000000,1.811000,1.639000,28.570000
75%,2017.000000,73.500000,1.790000,18.750000,15.000000,50.000000,3.190000,4.200000,4.750000,22.220000,...,41.670000,7.500000,5.560000,1.000000,0.000000,30.250000,10.750000,1.868000,1.681000,33.330000
max,2022.000000,78.250000,5.040000,43.750000,32.500000,81.250000,269.000000,4.500000,5.310000,38.890000,...,56.940000,10.250000,13.890000,2.500000,0.500000,32.750000,13.250000,2.065000,1.819000,55.000000

In [50]:
main_df.reset_index(inplace=True)

In [52]:
main_df.drop(columns=['index'],inplace=True)

In [54]:
main_df.loc[main_df['Par 3 Performance'] == 269]

,Name,Year,Scoring Average (Actual),Stroke Differential Field Average,Par 3 Birdie or Better Leaders,Par 4 Birdie or Better Leaders,Par 5 Birdie or Better Leaders,Par 3 Performance,Par 4 Performance,Par 5 Performance,...,One-Putt Percentage,1-Putts per Round,3-Putt Avoidance,3-Putts per Round,3+ Putts per Round,Putts Per Round,2-Putts per Round,Putting Average,Overall Putting Average,Birdie or Better Conversion Percentage
975,Marc Leishman,2019.0,72.25,-0.48,37.5,12.5,37.5,269.0,4.23,4.81,...,44.44,8.0,4.17,0.75,0.0,28.75,9.25,1.778,1.597,37.78

In [64]:
main_df.loc[975,'Par 3 Performance']=2.69

In [67]:
main_df.to_csv('csv/main_allyears_df.csv')